w

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -38,12 +38,25 @@ export_env_dir() {
 }
 export_env_dir "$ENV_DIR"
 
-ruby -v
-cd /app
-ls
-gem install bundler
-bundle update --ruby
-ruby -v
+if ! command -v erb &> /dev/null; then
+  echo "-----> An existing Ruby installation was not found (required for erb template support)"
+  ruby_version="3.2.1"
+  ruby_url="https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/${STACK}/ruby-${ruby_version}.tgz"
+  vendored_ruby_dir=".heroku-buildpack-libopaque/ruby"
+  mkdir -p "${BUILD_DIR}/${vendored_ruby_dir}"
+
+  if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 5 "${ruby_url}" | tar -zxC "${BUILD_DIR}/${vendored_ruby_dir}"; then
+    echo "     ! Failed to download Ruby from '${ruby_url}'" >&2
+    exit 1
+  fi
+
+  mkdir -p "${BUILD_DIR}/.profile.d"
+  # Deliberately pick the same profile.d script filepath as the Ruby buildpack,
+  # so if the Ruby buildpack comes after this one, it will overwrite this script.
+  echo "export PATH=\"\${HOME}/${vendored_ruby_dir}/bin:\${PATH}\"" > "${BUILD_DIR}/.profile.d/ruby.sh"
+
+  echo "-----> Installed Ruby ${ruby_version}"
+fi
 
 ### Compile
 
